version: '3.9'

services:
  db:
    image: postgres:14
    container_name: etm-backend-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: etm_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2
    container_name: etm-backend-redis
    ports:
      - "6379:6379"

  backend:
    build: .
    container_name: etm-backend-backend
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    entrypoint: ["./wait-for-db.sh", "db", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  db_data:
